#!/bin/bash

CWD=`pwd`


SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


INSTALL_DIR=${CWD}/install
MBEDTLS_BUILD_DIR=${CWD}/mbedtls-build
MBEDTLS_DIR=${CWD}/mbedtls
CURL_DIR=${CWD}/curl
CURL_BUILD_DIR=${CWD}/curl-build
EXAMPLE_BUILD_DIR=${CWD}/example

mkdir ${INSTALL_DIR}
mkdir ${MBEDTLS_BUILD_DIR}
mkdir ${EXAMPLE_BUILD_DIR}
mkdir ${MBEDTLS_DIR}
mkdir ${CURL_DIR}
mkdir ${CURL_BUILD_DIR}

cd ${MBEDTLS_DIR}
curl -sSL https://github.com/Mbed-TLS/mbedtls/archive/refs/tags/v3.4.0.tar.gz | tar -xzf - --strip-components=1

cd ${MBEDTLS_BUILD_DIR}
cp ${SCRIPT_DIR}/mbedtls-config/mbedtls_config.h ${MBEDTLS_DIR}/include/mbedtls
cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DENABLE_TESTING=OFF ${MBEDTLS_DIR}
make -j 16
make install

cd ${CURL_DIR}
curl -sSL https://github.com/curl/curl/releases/download/curl-8_2_1/curl-8.2.1.tar.gz | tar -xzf - --strip-components=1

#-DCURL_DISABLE_DICT=ON -DCURL_DISABLE_FILE=ON -DCURL_DISABLE_FTP=ON -DCURL_DISABLE_GOPHER=ON -DCURL_DISABLE_IMAP=ON -DCURL_DISABLE_LDAP=ON -DCURL_DISABLE_LDAPS=ON -DCURL_DISABLE_MQTT=ON -DCURL_DISABLE_POP3=ON -DCURL_DISABLE_SMB=ON -DCURL_DISABLE_SMTP=ON -DCURL_DISABLE_TELNET=ON -DCURL_DISABLE_TFTP=ON
cd ${CURL_BUILD_DIR}
cmake -DCMAKE_INSTALL_PREFIX=${INSTALL_DIR} -DCMAKE_POSITION_INDEPENDENT_CODE=ON -DCURL_USE_MBEDTLS=ON -DMbedTLS_DIR=${INSTALL_DIR}/lib/cmake/MbedTLS -DBUILD_SHARED_LIBS=OFF -DBUILD_STATIC_LIBS=ON -DCURL_ZLIB=OFF -DCURL_DISABLE_DICT=ON -DCURL_DISABLE_FILE=ON -DCURL_DISABLE_FTP=ON -DCURL_DISABLE_GOPHER=ON -DCURL_DISABLE_IMAP=ON -DCURL_DISABLE_LDAP=ON -DCURL_DISABLE_LDAPS=ON -DCURL_DISABLE_MQTT=ON -DCURL_DISABLE_POP3=ON -DCURL_DISABLE_SMB=ON -DCURL_DISABLE_SMTP=ON -DCURL_DISABLE_TELNET=ON -DCURL_DISABLE_TFTP=ON ${CURL_DIR}

make -j 16
make install

cd ${EXAMPLE_BUILD_DIR}
cmake -DNO_WEBSOCKET=ON  -DENABLE_MBEDTLS=ON -DUSE_MBEDTLS=ON -DNABTO_DEVICE_MBEDTLS_PROVIDER=package -DMbedTLS_DIR=${INSTALL_DIR}/lib/cmake/MbedTLS -DCURL_LIBRARY=${INSTALL_DIR}/lib/libcurl.a -DCURL_INCLUDE_DIR=${INSTALL_DIR}/include -DPC_MbedTLS_LIBRARY_DIRS=${INSTALL_DIR}/lib -DPC_MbedTLS_INCLUDE_DIRS=${INSTALL_DIR}/include ${SCRIPT_DIR}
make -j 16
