set(REF "2171055f9cfd6af4b82339dc7a63adee0abf1983")

vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO nabto/nabto-embedded-sdk
    REF ${REF}
    SHA512 8c219f34ea13df904d24f6a8953c76d96d7e75a7e96529af3d358636440cec17331148d8af96e1f97926c92c1f3bb18bd9d4ddfad599cd8c480aedcb3ead6482
    HEAD_REF "master"
)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    OPTIONS
        -DCMAKE_MODULE_PATH=${SOURCE_PATH}/cmake/vcpkg
        -DDEVICE_BUILD_EXAMPLES=FALSE
        -DDEVICE_BUILD_TESTS=FALSE
        -DDEVICE_BUILD_APPS=FALSE
        -DNABTO_DEVICE_PREFER_SYSTEM_LIBS=ON
        -DNABTO_DEVICE_USE_SYSTEM_LIBEVENT=ON
        -DNABTO_DEVICE_USE_SYSTEM_NABTOCOMMON=ON
        -DNABTO_DEVICE_USE_SYSTEM_MBEDTLS=ON
        -DNABTO_DEVICE_USE_SYSTEM_NLOHMANNJSON=ON
        -DNABTO_DEVICE_USE_SYSTEM_TINYCBOR=ON
        -DNABTO_DEVICE_BUILD_WITH_VCPKG_DEPENDENCIES=TRUE
        -DNABTO_DEVICE_VERSION="0.0.0+${REF}"
)

vcpkg_cmake_install()

vcpkg_copy_pdbs()

vcpkg_cmake_config_fixup(PACKAGE_NAME NabtoEmbeddedSDK CONFIG_PATH lib/cmake/NabtoEmbeddedSDK)


#vcpkg_install_copyright(FILE_LIST "${SOURCE_PATH}/LICENSING.md")
